### ISSUE TITLE
Crash when no LCs registered

### ISSUE THREAD

**Issue by fakedrake** [eestec/eestec.portal#20]
I am not really sure what we are supposed to do here. Ideally I guess we could have a warning and the user is created and the LC is added later on.
I find that to be an awesome educational excesrsize (the field is rendered differently) so I am doing it at some point just to get my teeth into it. If anyone has any other suggestions please let me know!

**Comment by fakedrake** [comment]
By the way, to reproduce this delete all LCs and go to /MY-site-name-whatever-it-is/personal-information. You will get a page not found.

**Comment by domenkozar** [comment]
Before using portal, you will need to add at least one LC. I'm currently working on fixture that will take care of that. I wouldn't complicate too much how to handle this. Only document that initial data import has to be done before using the portal.
