### ISSUE TITLE
"Event cancelled" notification email

### ISSUE THREAD

**Issue by zupo** [eestec/eestec.portal#24]
As per [our specifications](http://eestecportal.readthedocs.org/en/latest/specs/workflows/index.html#event-and-eventapplication-workflow), we need to send an email to the International Board whenever an event is cancelled.

The code for this task uses the code that sends an email when an Event is published, you just need to add another `if` caluse to check for `cancel` action.
- create a separate git branch for this issue
- amend `event_created` event subscriber in content/event.py so it also catches `cancel` actions and calls an appropriate method in `emails.py`
- add a method to send an email to emails/event.py (again, see how it's done when event is published)
- write a test for it, again refering to tests/test_event.py as a point of reference.
- the actual text for the email has not been written yet, take time to write up a nice email that the Board will receive when an LC will  cancel an event.

**Comment by balkian** [comment]
I have the code for this and issue 23. But I should "cancel" an event, and using the "cancel" action gives this error on the tests:

WorkflowException: No workflow provides the '${action_id}' action.

Same for "cancel-event" and "cancel_event"

**Comment by balkian** [comment]
Check the issue_24 branch. It is not fully working but this way someone can take over it if I'm not available these days.

**Comment by zupo** [comment]
The problem here is that the Event content type does not have a customized workflow yet. It uses the default Plone one, which does not have the "cancel" action. Hence the error.

Adding a workflow is kinda advanced topic, so I'll do it, and when we have it, you can continue working on this feature.

**Comment by zupo** [comment]
Pushed event_workflow to issue_24, you can now continue with this work.
