### ISSUE TITLE
Online Sprint

### ISSUE THREAD

**Issue by fakedrake** [eestec/eestec.portal#25]
Is there an official date for the online sprint?

**Comment by tsironis** [comment]
Yeah, we should know up front to be free to join!

**Comment by fakedrake** [comment]
According to the doodle it looks like Friday is the best date for it.

**Comment by andrejpan** [comment]
:) The sprint was on Monday evening. Are you not on our official email list(it@eestec.net)?

**Comment by tsironis** [comment]
I'm definitely not in the email list because I'm not an EESTEC member.

**Comment by domenkozar** [comment]
Who can add him to it@eestec.net?

**Comment by domenkozar** [comment]
@tsironis it's best if you join #ngep irc channel on freenode :)

We had a sprint yesterday. Write to it-coordinator@eestec.net to add you on the list :)
