### ISSUE TITLE
Handle exit codes in pre-commit-check.sh

### ISSUE THREAD

**Issue by zupo** [eestec/eestec.portal#3]
Currently the `pre-commit-check.sh` does not properly handle exit codes of commands it runs. As a consequence, the exit code of the entire script equals the exit code of the last command.

In other words: if `bin/test` fails and `bin/pep8` succeedes, the `pre-commit-check.sh` script will also succeed and Travis will claim the build was successful. 

To have proper handling of exit codes, use `handle_exit` function from one of [NiteoWeb's packages](https://github.com/niteoweb/spinrewriter/blob/master/pre-commit-check.sh) and use it the same way as it's used there.

**Comment by brodul** [comment]
Wouldn't be wise to just put the -e parameter behind /bin/bash.

It would be much cleaner.

**Comment by domenkozar** [comment]
Using `-e`  would exit the script on first error, we want to run all steps from the script and exit with non-zero if any of the scripts returned non-zero

**Comment by brodul** [comment]
Roger that. Will take a look.

**Comment by domenkozar** [comment]
Done in 4a358821333c02890fe33922a03488764936a304
