### ISSUE TITLE
Failed to load LC and Event icons

### ISSUE THREAD

**Issue by balkian** [eestec/eestec.portal#34]
![logo not found](https://f.cloud.github.com/assets/213135/347711/1ad8f2d6-9eed-11e2-97a5-f456383a7513.jpg)

**Comment by zupo** [comment]
OK, so each content type defines its icon in its XML:
- https://github.com/eestec/eestec.portal/blob/master/src/eestec/portal/profiles/default/types/eestec.portal.event.xml#L10
- https://github.com/eestec/eestec.portal/blob/master/src/eestec/portal/profiles/default/types/eestec.portal.eventapplication.xml#L10
- https://github.com/eestec/eestec.portal/blob/master/src/eestec/portal/profiles/default/types/eestec.portal.lc.xml#L8

These XML were copied over from the old Plone 3 codebase and the URLs for icons are incorrect in this new Plone 4 codebase. 

Actionplan:
- find icons in the old codebase: http://svn.plone.org/svn/collective/eestec.base/trunk/eestec/base/browser/icons/
- copy them to the new codebase into the theme/images folder: https://github.com/eestec/eestec.portal/tree/master/src/eestec/portal/browser/theme/images
- change URLs in XMLs to be ++theme++eestec.portal/images/<ICON_FILENAME_HERE>

**Comment by zupo** [comment]
Related to #1.
