### ISSUE TITLE
LC creation form only asks for City

### ISSUE THREAD

**Issue by balkian** [eestec/eestec.portal#40]
It should also ask for CP information.

**Comment by zupo** [comment]
LC's should be added with a custom form that is available on /Plone/@@add-lc.

We should override the default AddForm to redirect to @@add-lc form. Read here how to override AddForms: http://plone.org/products/dexterity/documentation/manual/developer-manual/advanced/forms

**Comment by balkian** [comment]
Fixed in commit da5309f1361dd8cb98b9c9d483b4ba544be433da

See issue #36

**Comment by zupo** [comment]
Pull Request for this issue: #43.
