### ISSUE TITLE
Add logo to eestec organization on GitHub

### ISSUE THREAD

**Issue by zupo** [eestec/eestec.portal#8]
You have to upload the logo to Gravatar.com then link it on GitHub. There are guides on how to do it, find them :).

**Comment by tsironis** [comment]
It should be done from the EESTEC board or someone who keeps all the passwords. I don't know exactly the structure of EESTEC but you get the point...! :)

**Comment by balkian** [comment]
We should probably ask for a nice design for the IT Team logo, EESTEC's logo doesn't look good squared.

**Comment by zupo** [comment]
I disagree, for me it looks perfectly fine like it is now.
