### ISSUE TITLE
Fix issue tracker URL

### ISSUE THREAD

**Issue by zupo** [eestec/eestec.portal#9]
The "Bug Tracker" url at http://eestecportal.readthedocs.org/en/latest/ currently points to http://dev.starzel.de/eestec, but it should point to https://github.com/eestec/eestec.portal/issues. ([Fix it!](https://raw.github.com/eestec/eestec.portal/master/README.rst)

**Comment by zupo** [comment]
You did? I see you as the one assigned.

**Comment by Arsku** [comment]
Yeah. Noone added me to team. So Roto did now.

**Comment by zupo** [comment]
Cool.
